config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'about' => 'homes#about'
  get 'confirmation' =>'members#confirmation'
  patch 'withdraw'  => 'members#withdraw'
  get 'empty' => 'cart_items#empty'
  post 'confirm' => 'orders#confirm'
  get 'thanks' => 'orders#thanks'

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
  }
  devise_for :members, controllers: {
    sessions:      'members/sessions',
    passwords:     'members/passwords',
    registrations: 'members/registrations'
  }

  resources :members, only: [:show, :edit, :update]
  resources :products, only: [:index, :show]
  resources :genres, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :cart_items, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :orders, only: [:new, :create, :index, :show]
  resources :order_products, only: [:index, :show]
  resources :deliveries, only: [:new, :create, :index, :edit, :update, :destroy]

  namespace :admin do
    resources :members, only: [:index, :show, :edit, :update]
    resources :products, only: [:new, :create, :index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :edit, :update]
    resources :order_products, only: [:index, :show, :edit, :update]
    get 'top' => 'orders#top'
    get "search" => "products#search"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :member
  belongs_to :product
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :member
  attr_accessor :full_address

  def full_address
    self.full_address = self.postal_code + self.address + self.name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products, dependent: :destroy

  enum is_active: { enable: true, disable: false }
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :deliveries, dependent: :destroy

  enum is_active: { enable: true, disable: false }

  def full_name
    return self.first_name + self.last_name
  end

  def active_for_authentication?
    super && self.is_active == 'enable'
  end

  def Member.search(search, member_or_product)
      if member_or_product == "1"
        Member.where(['first_name LIKE ?', "%#{search}%"])
      else
        Member.all
      end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :member

	has_many :order_products, dependent: :destroy

	enum order_status: [:waiting_payment, :payment_confirmation, :production, :preparing_shipping, :shipped]
  #入金待ち0 #入金確認1 #製作中2 #発送準備中3 #発送済4

  def total_quantity
    a = 0
    self.order_products.each do |order_product|
      a = a + order_product.quantity
    end
    return a
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
	belongs_to :order
	belongs_to :product

	enum production_status: [:cannot_strat, :waiting_production, :production, :production_completed]
    #着手不可 制作待ち 製作中 制作完了

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre

  has_many :cart_items, dependent: :destroy
  has_many :order_products, dependent: :destroy

  attachment :image

  enum is_sales_status: { sale: true, sold_out: false }

  def Product.search(search, member_or_product)
    if member_or_product == "2"
      Product.where(['name LIKE ?', "%#{search}%"])
    else
      Product.all
    end
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_member!

  def create
    product = Product.find(params[:product_id])
    cart_item = CartItem.find_by(product_id: product.id)
    if cart_item.blank?
      cart_item = CartItem.new(cart_item_params)
      cart_item.member_id = current_member.id
      cart_item.product_id = product.id
      cart_item.quantity = params[:cart_item][:quantity].to_i
    else
      cart_item.quantity += params[:cart_item][:quantity].to_i
    end
    cart_item.save
    redirect_to cart_items_path
  end

  def index
    @cart_items = current_member.cart_items
  end

  def update
    cart_item = CartItem.find(params[:id])
    cart_item.update(quantity: params[:cart_item][:quantity].to_i)
    redirect_to cart_items_path
  end

  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy
    redirect_to cart_items_path
  end

  def empty
    cart_items = current_member.cart_items
    cart_items.destroy_all
    redirect_to cart_items_path
  end

  private
    def cart_item_params
      params.require(:cart_item).permit(:member_id, :product_id, :quantity)
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :authenticate_admin!

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to genres_path
    else
      @genres = Genre.all
      render 'index'
    end
  end

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to genres_path
    else
      render "edit"
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
  	@genre.destroy
  	redirect_to genres_path
  end

  private
    def genre_params
      params.require(:genre).permit(:name, :is_active)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	PER = 3
  def top
  	@products = Product.all.page(params[:page]).per(PER)
  end

  def about
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_items_helper.rb
module CartsItemsHelper
end

app/helpers/delivelies_helper.rb
module DeliveliesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart_items/index.html.erb
<div class="row">
  <div class="col-xs-1"></div>
  <div class="col-xs-10">
    <h3 class="cart_item-title">ショッピングカート</h3>

    <div class="cart_item-emptybutton"><%= link_to "カートを空にする", empty_path,class:"btn btn-danger" %></div>

    <table class="table table-bordered table-hover cart_item-table">
      <thead>
        <tr class="success">
          <th>商品名</th>
          <th>単価(税込)</th>
          <th>数量</th>
          <th>小計</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @cart_items.each do |cart_item| %>
          <tr >
            <td>
              <%= attachment_image_tag cart_item.product, :image, :fill, 30, 30, fallback: "no-image-mini.jpg"  %>
              <%= cart_item.product.name %>
            </td>
            <td>
              <% taxed_price = cart_item.product.price * 1.1 %>
              <%= taxed_price.round.to_s(:delimited) %>
            </td>
            <td>
              <%= form_with model: cart_item, url: cart_item_path(cart_item), method: :patch do |f| %>
                <%= f.number_field :quantity %>
                <%= f.submit "更新", class:"btn btn-info" %>
              <% end %>
            </td>
            <td>
              <% taxed_total_price = taxed_price * cart_item.quantity %>
              <%= taxed_total_price.round.to_s(:delimited) %>
            </td>
            <td>
              <div class="cart_item-destroybutton"><%= link_to "削除する", cart_item_path(cart_item), method: :delete, class: "btn-sm btn-danger" %></div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-xs-1"></div>
  <div class="col-xs-7">
    <%= link_to "買い物を続ける", products_path, class:"btn btn-info" %>
  </div>
  <div class="col-xs-3">
    <table class="table table-bordered aaa">
      <tbody>
          <tr>
            <th class="success">合計金額</th>
            <td>
              <% @total_price = 0 %>
              <% @cart_items.each do |cart_item| %>
                <% @total_price += cart_item.product.price * cart_item.quantity %>
                <% taxed_total_price = @total_price * 1.1 %>
                <% @sum = taxed_total_price.round.to_s(:delimited) %>
              <% end %>
              <%= @sum %>
            </td>
          </tr>
      </tbody>
    </table>
  </div>
  <div class="col-xs-1"></div>
</div>

<div class="cart_item-orderbutton"><%= link_to "情報入力に進む", new_order_path, class:"btn btn-success btn-lg" %></div>