config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'about' => 'homes#about'
  get 'confirmation' =>'members#confirmation'
  patch 'withdraw'  => 'members#withdraw'
  get 'empty' => 'cart_items#empty'
  post 'confirm' => 'orders#confirm'
  get 'thanks' => 'orders#thanks'

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
  }
  devise_for :members, controllers: {
    sessions:      'members/sessions',
    passwords:     'members/passwords',
    registrations: 'members/registrations'
  }

  resources :members, only: [:show, :edit, :update]
  resources :products, only: [:index, :show]
  resources :genres, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :cart_items, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :orders, only: [:new, :create, :index, :show]
  resources :order_products, only: [:index, :show]
  resources :deliveries, only: [:new, :create, :index, :edit, :update, :destroy]

  namespace :admin do
    resources :members, only: [:index, :show, :edit, :update]
    resources :products, only: [:new, :create, :index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :edit, :update]
    resources :order_products, only: [:index, :show, :edit, :update]
    get 'top' => 'orders#top'
    get "search" => "products#search"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :member
  belongs_to :product
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :member
  attr_accessor :full_address

  def full_address
    self.full_address = self.postal_code + self.address + self.name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products, dependent: :destroy

  enum is_active: { enable: true, disable: false }
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :deliveries, dependent: :destroy

  enum is_active: { enable: true, disable: false }

  def full_name
    return self.first_name + self.last_name
  end

  def active_for_authentication?
    super && self.is_active == 'enable'
  end

  def Member.search(search, member_or_product)
      if member_or_product == "1"
        Member.where(['first_name LIKE ?', "%#{search}%"])
      else
        Member.all
      end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :member

	has_many :order_products, dependent: :destroy

	enum order_status: [:waiting_payment, :payment_confirmation, :production, :preparing_shipping, :shipped]
  #入金待ち0 #入金確認1 #製作中2 #発送準備中3 #発送済4

  def total_quantity
    a = 0
    self.order_products.each do |order_product|
      a = a + order_product.quantity
    end
    return a
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
	belongs_to :order
	belongs_to :product

	enum production_status: [:cannot_strat, :waiting_production, :production, :production_completed]
    #着手不可 制作待ち 製作中 制作完了

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre

  has_many :cart_items, dependent: :destroy
  has_many :order_products, dependent: :destroy

  attachment :image

  enum is_sales_status: { sale: true, sold_out: false }

  def Product.search(search, member_or_product)
    if member_or_product == "2"
      Product.where(['name LIKE ?', "%#{search}%"])
    else
      Product.all
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @product = Product.new
    @genres = Genre.all
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path
    else
      @products = Product.all.order(id: :desc)
      render :index
    end
  end

  def index
    @products = Product.page(params[:page]).per(10)
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
    @genres = Genre.all
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_product_path(@product)
    else
      render :edit
    end
  end

  def search
    @member_or_product = params[:option]
    if @member_or_product == "1"
      @members = Member.search(params[:search], @member_or_product)
    else
      @products = Product.search(params[:search], @member_or_product)
    end
  end

  private
    def product_params
        params.require(:product).permit(:image, :name, :explanatory, :genre_id, :price, :is_sales_status)
    end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :authenticate_admin!

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to genres_path
    else
      @genres = Genre.all
      render 'index'
    end
  end

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to genres_path
    else
      render "edit"
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
  	@genre.destroy
  	redirect_to genres_path
  end

  private
    def genre_params
      params.require(:genre).permit(:name, :is_active)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	PER = 3
  def top
  	@products = Product.all.page(params[:page]).per(PER)
  end

  def about
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
      @genres  = Genre.all
      p params[:i].class
      if params[:i]
        products = Product.where(genre_id: params[:i])
        @products = products.page(params[:page]).per(5)
      else
        @products = Product.page(params[:page]).per(5)
      end
  end

  def show
    @product = Product.find(params[:id])
    @cart_item = CartItem.new
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_items_helper.rb
module CartsItemsHelper
end

app/helpers/delivelies_helper.rb
module DeliveliesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<div class="row">
  <div class="col-xs-1"></div>
  <div class="col-xs-10">
    <h3 class="admin-products-title">商品編集画面</h3>

    <%= form_with model: @product, url: admin_product_path(@product) do |f| %>

      <div class="admin-products-image"><%= attachment_image_tag @product, :image, :size =>'150x120', fallback: "no_image.jpg" %></div>
      <%= f.attachment_field :image %>

      <h4>商品名</h4>
      <%= f.text_field :name, class: "form-control" %>

      <h4>商品説明</h4>
      <%= f.text_area :explanatory, class: "form-control" %>

      <h4>ジャンル</h4>
      <%= f.collection_select :genre_id, @genres, :id, :name, {include_blank: "---"} %>

      <h4>値段</h4>
      <%= f.text_field :price, class: "form-control" %>

      <h4>販売ステータス</h4>
      <%= f.select :is_sales_status, Product.is_sales_statuses.keys.map {|k| [I18n.t("enums.product.is_sales_status.#{k}"), k]} %>

      <%= f.submit '変更を保存', class: "btn btn-info btn-lg btn-block admin-products-create" %>

    <% end %>
  </div>
  <div class="col-xs-1"></div>
</div>

app/views/admin/products/index.html.erb
<div class="row">
  <div class="col-xs-1"></div>
  <div class="col-xs-10">
    <h3 class="admin-products-title">商品一覧画面</h3>
    <div class="admin-products-new"><%= link_to '', new_admin_product_path, class: "glyphicon glyphicon-plus-sign admin-products-icon" %></div>
    <table class="table table-hover admin-products-table">
      <thead>
        <tr class="success">
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜き価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.id %></td>
            <td><%= link_to product.name, admin_product_path(product) %></td>
            <td><%= product.price.to_s(:delimited) %></td>
            <td><%= product.genre.name %></td>
            <td><%= product.is_sales_status_i18n %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="admin-products-paginate"><%= paginate @products, class: "paginate" %></div>
  </div>
  <div class="col-xs-1"></div>
</div>

app/views/admin/products/new.html.erb
<div class="row">
  <div class="col-xs-1"></div>
  <div class="col-xs-10">
    <h3 class="admin-products-title">商品新規登録画面</h3>
    <%= form_with model: @product, url: admin_products_path do |f| %>
      <%= f.attachment_field :image %>
      <h4>商品名</h4>
      <%= f.text_field :name, class: "form-control" %>
      <h4>商品説明</h4>
      <%= f.text_area :explanatory, class: "form-control" %>
      <h4>ジャンル</h4>
      <%= f.collection_select :genre_id, @genres, :id, :name, {include_blank: true}, {class: "form-control"} %>
      <h4>値段</h4>
      <%= f.text_field :price, class: "form-control" %>
      <h4>販売ステータス</h4>
      <%= f.select :is_sales_status, Product.is_sales_statuses.keys.map {|k| [I18n.t("enums.product.is_sales_status.#{k}"), k]}, {}, class: "form-control" %><br>
      <%= f.submit '新規登録', class: "btn btn-info btn-lg btn-block admin-products-create" %>
    <% end %>
  </div>
  <div class="col-xs-1"></div>
</div>

app/views/admin/products/search.html.erb
<div class="row">
  <div class="col-xs-1"></div>
  <div class="col-xs-10">
    <% if @member_or_product == "1"%>
      <h3>会員検索一覧</h3>
      <table class="table table-hover genres-table">
        <thead>
            <tr class="success">
                <th>会員ID</th>
                <th>氏名</th>
                <th>メールアドレス</th>
                <th>ステータス</th>
            </tr>
        </thead>
        <tbody>
            <% @members.each do |member| %>
                <tr>
                    <td><%= member.id %></td>
                    <td><%= link_to member.full_name, admin_member_path(member) %></td>
                    <td><%= member.email %></td>
                    <td><%= member.is_active_i18n %></td>
                </tr>
            <% end %>
        </tbody>
      </table>

    <% elsif @member_or_product == "2" %>
      <h3>商品検索一覧</h3>
      <table class="table table-hover genres-table">
        <thead>
          <tr class="success">
              <th>商品ID</th>
              <th>商品名</th>
              <th>税抜き価格</th>
              <th>ジャンル</th>
              <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
              <tr>
                <td><%= product.id %></td>
                <td><%= link_to product.name, admin_product_path(product) %></td>
                <td><%= product.price.to_s(:delimited) %></td>
                <td><%= product.genre.name %></td>
                <td><%= product.is_sales_status_i18n %></td>
              </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
    <% end %>
  </div>
  <div class="col-xs-1"></div>
</div>

app/views/admin/products/show.html.erb
<div class="row">
  <div class="col-xs-4"></div>
  <div class="col-xs-4">
    <h3 class="admin-products-title">商品詳細画面</h3>
    <div class="thumbnail">
      <%= attachment_image_tag @product, :image, :size =>'150x120', fallback: "no_image.jpg" %>
      <div class="caption">
        <p>【商品名】<span class="admin-products-text"><%= @product.name %></span></p>
        <p>【商品説明】<span class="admin-products-text"><%= @product.explanatory %></span></p>
        <p>【ジャンル】<span class="admin-products-text"><%= @product.genre.name %></span></p>
        <% taxed_price = @product.price.to_i * 1.1 %>
        <p>【税込価格(税抜価格)】<span class="admin-products-text"><%= taxed_price.round.to_s(:delimited) %> (<%= @product.price.to_s(:delimited) %>)円</span></p>
        <p>【販売ステータス】<span class="admin-products-text"><%= @product.is_sales_status_i18n %></span></p>
      </div>
    </div>
    <div class=" admin-products-editbutton"><%= link_to "編集する", edit_admin_product_path(@product), class: "btn btn-primary" %></div>
  </div>
  <div class="col-xs-4"></div>
</div>

app/views/products/index.html.erb
<div class="row">
    <div class="col-xs-1"></div>
    <div class="genre">
      <div class="col-xs-2">
        <%= form_with url: products_path, method: :get, local: true do |f| %>
        <%= f.collection_select :i, Genre.all, :id, :name, :include_blank => "-------" %>
        <%= f.submit "ジャンル検索" %>
        <% end %>
      </div>
    </div>
    <div class="col-xs-9">
      <h3>商品一覧</h3>
      <% @products.each do |product| %>
      <div class="product-items clearfix">
        <p><%= link_to product_path(product) do %>
        <%= attachment_image_tag product, :image, :fill, 150, 100, fallback: "no_image.jpg" %>
        <% end %><p>
        <p><%= product.name %></p>
        <p><%= number_to_currency(product.price, :format => "%u%n", :unit => "￥") %></p>
      </div>
      <% end %>
    </div>
</div>
<div class="pagi">
  <%= paginate @products, class: "paginate" %>
</div>

app/views/products/show.html.erb
<div class="row doto">
	<div class="col-xs-1"></div>
	<div class="col-xs-2">
		<%= form_with url: products_path, method: :get, local: true do |f| %>
      <%= f.collection_select :i, Genre.all, :id, :name, :include_blank => "-------" %>
      <%= f.submit "ジャンル検索" %>
		<% end %>
	</div>

	<div class="col-xs-3">

		<%= attachment_image_tag @product, :image, :size =>'150x120', fallback: "no_image.jpg" %>
	</div>
	<div class="col-xs-5">

		<div class="text">
			<p>商品名<%= @product.name %></p>

			<p>商品説明 <%= @product.explanatory %></p>

			<% taxed_price = @product.price.to_i * 1.1 %>
			<p>¥<%= taxed_price.round %>(税込)</p>
      <% if member_signed_in? %>
        <%= form_with model: @cart_item, url: cart_items_path, local: true do |f| %>
          <%= hidden_field_tag :product_id, @product.id %>
          <%= f.select :quantity, [['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5]], { include_blank: "数量選択" } %>
          <%= f.submit "カートに入れる", class: "btn btn-primary" %>
        <% end %>
      <% end %>
		</div>



		<div class="col-xs-1"></div>
	</div>
</div>