config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'about' => 'homes#about'
  get 'confirmation' =>'members#confirmation'
  patch 'withdraw'  => 'members#withdraw'
  get 'empty' => 'cart_items#empty'
  post 'confirm' => 'orders#confirm'
  get 'thanks' => 'orders#thanks'

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
  }
  devise_for :members, controllers: {
    sessions:      'members/sessions',
    passwords:     'members/passwords',
    registrations: 'members/registrations'
  }

  resources :members, only: [:show, :edit, :update]
  resources :products, only: [:index, :show]
  resources :genres, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :cart_items, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :orders, only: [:new, :create, :index, :show]
  resources :order_products, only: [:index, :show]
  resources :deliveries, only: [:new, :create, :index, :edit, :update, :destroy]

  namespace :admin do
    resources :members, only: [:index, :show, :edit, :update]
    resources :products, only: [:new, :create, :index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :edit, :update]
    resources :order_products, only: [:index, :show, :edit, :update]
    get 'top' => 'orders#top'
    get "search" => "products#search"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :member
  belongs_to :product
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :member
  attr_accessor :full_address

  def full_address
    self.full_address = self.postal_code + self.address + self.name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products, dependent: :destroy

  enum is_active: { enable: true, disable: false }
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :deliveries, dependent: :destroy

  enum is_active: { enable: true, disable: false }

  def full_name
    return self.first_name + self.last_name
  end

  def active_for_authentication?
    super && self.is_active == 'enable'
  end

  def Member.search(search, member_or_product)
      if member_or_product == "1"
        Member.where(['first_name LIKE ?', "%#{search}%"])
      else
        Member.all
      end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :member

	has_many :order_products, dependent: :destroy

	enum order_status: [:waiting_payment, :payment_confirmation, :production, :preparing_shipping, :shipped]
  #入金待ち0 #入金確認1 #製作中2 #発送準備中3 #発送済4

  def total_quantity
    a = 0
    self.order_products.each do |order_product|
      a = a + order_product.quantity
    end
    return a
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
	belongs_to :order
	belongs_to :product

	enum production_status: [:cannot_strat, :waiting_production, :production, :production_completed]
    #着手不可 制作待ち 製作中 制作完了

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre

  has_many :cart_items, dependent: :destroy
  has_many :order_products, dependent: :destroy

  attachment :image

  enum is_sales_status: { sale: true, sold_out: false }

  def Product.search(search, member_or_product)
    if member_or_product == "2"
      Product.where(['name LIKE ?', "%#{search}%"])
    else
      Product.all
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	PER = 3
  def top
  	@products = Product.all.page(params[:page]).per(PER)
  end

  def about
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_items_helper.rb
module CartsItemsHelper
end

app/helpers/delivelies_helper.rb
module DeliveliesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- コード追加 Bootstrap CSS読み込みコード-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if member_signed_in? %>
      <div class="welcome-text">
        ようこそ <%= link_to current_member.full_name, member_path(current_member) %> さん !
      </div>
    <% end %>
    <% if admin_signed_in? %>
      <div class="search-form">
        <%= form_tag admin_search_path, method: :get do %>
          <%= text_field_tag :search, '', placeholder: "会員名 or 商品名" %>
          <%= select_tag(:option, options_for_select([["会員", "1"],["商品","2"]]))%>
          <%= submit_tag '検索', class: "btn btn-primary" %>
        <% end %>
      </div>
    <% end %>

    <div id="sp-menu">
      <h2>G20</h2>
      <ul>
        <% if member_signed_in? %>
          <li><%= link_to "マイページ", member_path(current_member) %></li>
          <li><%= link_to "商品一覧", products_path %></li>
          <li><%= link_to "カート", cart_items_path %></li>
          <li><%= link_to "ログアウト", destroy_member_session_path, method: :delete %></li>
        <% elsif admin_signed_in? %>
          <li><%= link_to "商品一覧", admin_products_path %></li>
          <li><%= link_to "会員一覧", admin_members_path %></li>
          <li><%= link_to "注文履歴一覧", admin_orders_path %></li>
          <li><%= link_to "ジャンル管理", genres_path %></li>
          <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
        <% else %>
          <% unless request.path.include?("admins/sign_in") %>
            <li><%= link_to "アバウト", about_path %></li>
            <li><%= link_to "商品一覧", products_path %></li>
            <li><%= link_to "新規登録", new_member_registration_path %></li>
            <li><%= link_to "ログイン", new_member_session_path %></li>
          <% end %>
        <% end %>
      </ul>
    </div>

    <div id="hm-icon">
      <a class="menu-trigger" href="#">
        <span></span>
        <span></span>
        <span></span>
      </a>
    </div>

    <div class="container">
      <%= yield %>
    </div>
    <footer class="footer">
      <div class="content-wrapper">
        <div class="address">
          <p>G20<br />
            〒000−0000 <br />
            東京都×××××××××× <br />
            TEL 01-2345-6789 <br />
            FAX 01-2345-6789
          </p> 
        </div>
        <ul class="text">
          <li><a href="#">トップページ</a></li>
          <li><a href="#">会社概要</a></li>
          <li><a href="#">事業内容</a></li>
          <li><a href="#">採用情報</a></li>
          <li><a href="#">お問い合わせ</a></li>
        </ul>
      </div>
      <div class="copylight">
        <p>©️ G20., Ltd. All Rights Reserved.</p>
      </div>
    </footer>
  </body>
</html>