config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'about' => 'homes#about'
  get 'confirmation' =>'members#confirmation'
  patch 'withdraw'  => 'members#withdraw'
  get 'empty' => 'cart_items#empty'
  post 'confirm' => 'orders#confirm'
  get 'thanks' => 'orders#thanks'

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
  }
  devise_for :members, controllers: {
    sessions:      'members/sessions',
    passwords:     'members/passwords',
    registrations: 'members/registrations'
  }

  resources :members, only: [:show, :edit, :update]
  resources :products, only: [:index, :show]
  resources :genres, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :cart_items, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :orders, only: [:new, :create, :index, :show]
  resources :order_products, only: [:index, :show]
  resources :deliveries, only: [:new, :create, :index, :edit, :update, :destroy]

  namespace :admin do
    resources :members, only: [:index, :show, :edit, :update]
    resources :products, only: [:new, :create, :index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :edit, :update]
    resources :order_products, only: [:index, :show, :edit, :update]
    get 'top' => 'orders#top'
    get "search" => "products#search"
  end
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :deliveries, dependent: :destroy

  enum is_active: { enable: true, disable: false }

  def full_name
    return self.first_name + self.last_name
  end

  def active_for_authentication?
    super && self.is_active == 'enable'
  end

  def Member.search(search, member_or_product)
      if member_or_product == "1"
        Member.where(['first_name LIKE ?', "%#{search}%"])
      else
        Member.all
      end
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @members = Member.page(params[:page]).per(10)
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to admin_member_path(@member.id)
    else
      render :edit
    end
  end

  private
    def member_params
      params.require(:member).permit(:name, :first_name, :last_name, :reading_first_name, :reading_last_name, :postal_code, :address, :phone_number, :email, :is_active)
    end
end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

class Members::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    products_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

class Members::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

    protected

  def reject_member
    @member = Member.find_by(email: params[:member][:email].downcase)
    if @member
      if (@member.valid_password?(params[:member][:password]) && (@member.active_for_authentication? == 'enable'))
        redirect_to new_member_session_path
      end
    end
  end
end

app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_member!

	def show
    @member = Member.find(params[:id])
	end

	def edit
		@member = Member.find(params[:id])
	end

	def update
		@member = Member.find(params[:id])
		@member.update(member_params)
    redirect_to member_path(@member.id)
	end

	def confirmation
	end

  def withdraw
    @member = Member.find_by(id: current_member.id)
    if @member.is_active == 'enable'
      @member.is_active = 'disable'
    else
      @member.is_active = 'enable'
    end
    @member.save
    reset_session
    redirect_to	root_path
  end


	private

	def member_params
    params.require(:member).permit(:first_name, :last_name, :reading_first_name, :reading_last_name, :postal_code, :address, :phone_number, :email, :is_active)
	end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/confirmation.html.erb
<h3>本当に退会しますか？</h3>
<br>
<p>退会すると、会員情報や</p>
<br>
<p>これまでの購入履歴が閲覧できなくなります。</p>
<br>
<p>退会する場合は、「退会する」をクリックしてください。</p>
<br>
<table>
<span><%= link_to '退会しない', member_path(current_member.id), class: "btn btn-success" %></span>
<span>　　<%= link_to '退会する', withdraw_path, method: :patch, "data-confirm" => "退会しますか？",  class: "btn btn-danger" %></span>
</table>

app/views/members/edit.html.erb
<h1>登録情報変更</h1>

<%= form_for (@member) do |f| %>

<table class='member_edit'>
<tbody>
<tr>
 <th class='member_e_th'>名前</th>
 <td>
 <span>(姓)<%= f.text_field :first_name, value:@member.first_name %></span>
 <span>(名)<%= f.text_field :last_name, value:@member.last_name %></span>
 </td>
</tr>

<br>

<tr>
 <th class='member_e_td'>フリガナ</th>
 <td>
 <span>(セイ)<%= f.text_field :reading_first_name, value:@member.reading_first_name %></span>
 <span>(メイ)<%= f.text_field :reading_last_name, value:@member.reading_last_name %></span>
 </td>
</tr>

<br>

<tr>
 <th class='member_e_th'>メールアドレス</th>
 <td class='member_e_td'><%= f.text_field :email, value:@member.email %></td>
</tr>

<br>

<tr>
 <th class='member_e_th'>郵便番号(ハイフンなし)</th>
 <td class='member_e_td'><%= f.text_field :postal_code, value:@member.postal_code %></td>
</tr>

<br>

<tr>
 <th class='member_e_th'>住所</th>
 <td class='member_e_td'><%= f.text_field :address, value:@member.address, :size => "60*60" %></td>
</tr>

<br>

<tr>
 <th class='member_e_th'>電話番号(ハイフンなし)</th>
 <td class='member_e_td'><%= f.text_field :phone_number, value:@member.phone_number %></td>
</tr>

</tbody>
</table>

<br>

<span>
<%= f.submit "変更を保存する", class: "btn btn-primary" %>　　　
<% end %>
<%= link_to '退会する', confirmation_path, class: "btn btn-danger" %>
</span

app/views/members/show.html.erb
  
<h3>マイページ</h3>
<br>
<div class=members_s_info1>
  <span>登録情報</span>
  <span><%= link_to '編集する', edit_member_path(current_member.id), class: "btn btn-primary" %></span>
  <span><%= link_to 'パスワードを変更する', edit_member_registration_path, class: "btn btn-primary" %></span>
</div>

<br>

<table class="members_s_table">

<tr>
	  <th><span>氏名</span></th>
		<td><span><%= @member.first_name+@member.last_name %></span></td>
</tr>

<tr>
	  <th><span>カナ</span></th>
		<td><span><%= @member.reading_first_name+@member.reading_last_name %></span></td>
</tr>

<tr>
	  <th><span>郵便番号</span></th>
		<td><span><%= @member.postal_code %></span></td>
</tr>

<tr>
	  <th><span>住所</span></th>
		<td><span><%= @member.address %></span></td>
</tr>

<tr>
	  <th><span>電話番号</span></th>
		<td><span><%= @member.phone_number %></span></td>
</tr>

<tr>
	  <th><span>メールアドレス</span></th>
		<td><span><%= @member.email %></span></td>
</tr>

</table>

<br>

<div class="members_s_info2">
 <span>配送先</span>
 <span><%= link_to '一覧を見る', deliveries_path, class: "btn btn-primary" %></span>
 <span>　　注文履歴</span>
 <span><%= link_to '一覧を見る', orders_path, class: "btn btn-primary" %></span>
 </div>